addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update
 - sudo apt-get install libcups2-dev cups

install:
 - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
 - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
 - travis_install_nightly 7.0
 - pip install coveralls flake8
 - pip install pycups==1.9.66
 - pip install PyPDF2==1.18
 - pip install requests
 - git clone https://github.com/OCA/reporting-engine -b 7.0 $HOME/reporting-engine

script:
    - travis_run_flake8
    - travis_run_tests 7.0 $HOME/reporting-engine

after_success:
  coveralls
